### PR TITLE
Add WasmEdge lfx 2022 summer

### PR DESCRIPTION
**Pull request by hydai**
Signed-off-by: hydai <z54981220@gmail.com>

### CODE REVIEW

**Comment by nate-double-u** [comment]
Hi @hydai , could you please provide me the mentor's email addresses? (I have Michael's already) I need them to add them as a mentor. (here, in Slack, or by email at [natew@cncf.io](mailto:natew@cncf.io))

**Comment by nate-double-u** [comment]
Hi @hydai , could you please provide me the mentor's email addresses? (I have Michael's already) I need them to add them as a mentor. (here, in Slack, or by email at [natew@cncf.io](mailto:natew@cncf.io))

**Comment by hydai** [comment]
> Hi @hydai , could you please provide me the mentor's email addresses? (I have Michael's already) I need them to add them as a mentor. (here, in Slack, or by email at [natew@cncf.io](mailto:natew@cncf.io))

WenShuo Yang: highmagic[at]outlook.com
Hung-Ying Tai: hydai[at]secondstate.io
Yi-Ying He: yiying[at]secondstate.io

Thanks :-)

**Comment by nate-double-u** [comment]
Thanks, updated!

**Pull request merged**
