### PR TITLE
Add Knative Onboarding Research

### PR DESCRIPTION
**Pull request by Leo6Leo**
Added Knative proposals for LFX mentorship summer 2024

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Thanks for this @Leo6Leo and @mmejia02.

@mmejia02, could you thumbs up or approve this PR as well to confirm participation?

When we load this into the LFX platform, would you like candidates to provide a writing sample as a part of the application process? If you think that would be helpful I can make it a requirement of application.

**Comment by nate-double-u** [comment]
Also, thanks for getting your proposal in on the original due date -- we have updated [this term's schedule](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/README.md) to push things back a couple weeks, and the new due date is May 8th.

**Comment by Leo6Leo** [comment]
@nate-double-u Hello Nate, thanks for reviewing our application! The text below is the requirement for our application. Originally we thought to post it in our upstream issue when our project get approved by LFX.

I think we can leave the requirement in the upstream issue, so that candidates will actually take time to read the issue and understand the requirement themselves!  @mmejia02 lmk what do you think too!

---

**Application for LFX mentorship 2024 Term 2:**
This is primarily a research project and we would like to see how different candidates would approach the question of: How can we better the user experience of new end users within Knative Eventing? 

To see how you would approach this issue, you will **submit a research plan** which should contain:
- What are your research goals
- What research methods would you use to meet these goals and why?
- How are you planning on recruiting participants
- How will you know the study was successful (think: Key Performance Indicators)
- What would be the timeline of this project? (keep in mind that LFX is a 12 week program)
- What ethical concerns and considerations do you have?
- The plan can be as long or as short as you need it to be.

*Submit this plan as your cover letter*. There is no need to write a regular cover letter for this application, only the research plan and resume. 

**Submission Process:**
Please send your application via email to both myself @Leo6Leo  and ([leoli@redhat.com](mailto:leoli@redhat.com)) and @mmejia02 ([mariana.mejia@ocadu.ca](mailto:mariana.mejia@ocadu.ca)) by the time stated on LFX 

**Selection Process:**
We will be anonymizing your research plans and grading them. This will make the process transparent. We will then be looking at resumes which for obvious reasons cannot be anonymized, but we will not be placing a great emphasis on past experience. 

We will be factoring to an extent previous experience with open source, cloud technologies, user experience and user research. The reason we will not be placing a large emphasis on past experience is that this is meant to be a beginner friendly project, and we wish to give people that are completely new to the space a chance!

**Comment by nate-double-u** [comment]
That's easier for me, I like it! And that's a good process to go through, I like asking the candidates to write up proposals. You'll likely get more engaged folks that way. I do recommend that when applications do start coming in, don't just rely on the proposals though, also reach out to your favourite candidates (ChatGPT can do a lot to make a proposal look good, it's important to chat with folks too).

**Comment by nate-double-u** [comment]
(oh, and you can find info on how to fix the DCO issue here: https://github.com/cncf/mentoring/pull/1215/checks?check_run_id=24219386052)

**Comment by nate-double-u** [comment]
(hold is just for 👍 or approval from the other mentors 🙂)

**Comment by aliok** [comment]
Great stuff @Leo6Leo @mmejia02! So happy to see this proposal part of the Knative community!

**Comment by nate-double-u** [comment]
Made some formatting changes when I fixed the conflicts (adding more space around projects)

**Pull request merged**
