### PR TITLE
docs: add the CAPG GPU project

### PR DESCRIPTION
**Pull request by richardcase**
A small update to the proposed projects for the summer 2022 LFX
mentorship program. Cluster API Provider GCP would like to add support
for GPUs.

Signed-off-by: Richard Case <richard@weave.works>

/cc @dims @cpanato

### CODE REVIEW

**Comment by richardcase** [comment]
> Could you provide me the email addresses for the mentors? Either here or via DM in the CNCF slack would be fine.

Sent them to you via the CNCF slack.

**Review by nate-double-u — APPROVED** [review]
Thanks @richardcase!

**Comment by nate-double-u** [comment]
(force push to sign commit correctly.)

**Comment by cpanato** [comment]
thanks!

**Pull request merged**
