### PR TITLE
Add project information for SMI & Service Mesh

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by leecalcote** [comment]
@kushthedude 👍 

@zacharysarah hopefully, this save you a few clicks.

**Comment by zacharysarah** [comment]
@leecalcote Thanks!

**Comment by zacharysarah** [comment]
@idvoretskyi Can you approve please?

**Comment by kushthedude** [comment]
Thanks @idvoretskyi @zacharysarah !

**Pull request merged**
