### PR TITLE
add KubeArmor LFX Term-2 projects

### PR DESCRIPTION
**Pull request by Ankurk99**
- Implement DNS visibility with KubeArmor - https://github.com/kubearmor/KubeArmor/issues/1219
- Manage KubeArmor policies using OCI registry and use OCI hooks for container events - https://github.com/kubearmor/KubeArmor/issues/1130

### CODE REVIEW

**Review by aliok — APPROVED** [review]
Thanks!

**Comment by aliok** [comment]
Some relevant note: 
@Ankurk99 I saw mentors' names in KubeArmor's MAINTAINERS file but you might want to update https://github.com/cncf/foundation/blob/main/project-maintainers.csv as well

**Comment by nate-double-u** [comment]
> Some relevant note:
> @Ankurk99 I saw mentors' names in KubeArmor's MAINTAINERS file but you might want to update https://github.com/cncf/foundation/blob/main/project-maintainers.csv as well

+1

I noted this too—sometimes the CNCF list drifts out of sync with reality.

**Comment by Ankurk99** [comment]
> Some relevant note:
@Ankurk99 I saw mentors' names in KubeArmor's MAINTAINERS file but you might want to update [cncf/foundation@main/project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv?rgh-link-date=2023-05-09T17%3A22%3A39Z) as well

Thanks @aliok, I will update the list.

**Pull request merged**
