### PR TITLE
Add etcdadm integrate with cluster api ideas

### PR DESCRIPTION
**Pull request by prksu**
cc @dlipovetsky

### CODE REVIEW

**Comment by dlipovetsky** [comment]
lgtm

**Comment by idvoretskyi** [comment]
Closing as the deadline has passed.

**Comment by idvoretskyi** [comment]
@prksu you are welcome to submit your proposal to Community Bridge instead - https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md.

**Comment by prksu** [comment]
@idvoretskyi i have submitted gsoc proposal of this idea before (in the student application period). this PR only for listing.

**Pull request closed without merging**
