### PR TITLE
Adding LitmusChaos to LFX-23-Q1

### PR DESCRIPTION
**Pull request by imrajdas**
#### Improve code quality and add unit tests of litmus chaos components
- Description:  [LitmusChaos](https://litmuschaos.io) is an open-source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way. This project aims to improve the code quality of the golang components of litmus chaos and refactor the codebase for adding the unit test cases. 
- Expected Outcome: This will help the project to improve code quality, enhance the unit test suite, and identification of weaknesses
- Recommended Skills: Golang, Kubernetes
- Mentor: Amit Kumar Das (@amityt, amit.das@harness.io)  Sayan Mondal (@S-ayanide, sayan.mondal@harness.io)
- Upstream Issue: https://github.com/litmuschaos/litmus/issues/3892

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Hi @imrajdas, thanks for this proposal!

However, we do need a maintainer to participate in mentorship projects -- are you able to add someone from the [LitmusChaos maintainers group](https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L554) to work with you as a mentor as well?

**Comment by nate-double-u** [comment]
> Hi @imrajdas, thanks for this proposal!
> 
> However, we do need a maintainer to participate in mentorship projects -- are you able to add someone from the [LitmusChaos maintainers group](https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L554) to work with you as a mentor as well?

Note, sometimes this list drifts out of date -- if you are a maintainer, @imrajdas (forgive me for not knowing), could you update the the cncf/foundation list?

**Comment by imrajdas** [comment]
Hey @nate-double-u , I am also a maintainer of Litmuschaos. Tagging @ksatchit here.

**Review by nate-double-u — APPROVED** [review]
Thanks for the updates, I see the foundation list has been updated as well.

**Pull request merged**
