### PR TITLE
Add Vitess/Arewefastyet project proposal for LFX internship

### PR DESCRIPTION
**Pull request by frouioui**
This PR adds the Vitess `Rework the frontend UI of Vitess’ benchmarking tools` project to the list of project ideas for the LFX internship June-August in 2023.

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Thanks for this @fouioui & @rohit-nayak-ps!

I have planetscale email addresses for you — are these what you would like me to use?

**Comment by frouioui** [comment]
> I have planetscale email addresses for you — are these what you would like me to use?

Correct, those email addresses work fine!

**Review by aliok — APPROVED** [review]
Thanks @fouioui and @rohit-nayak-ps . Let's merge this one as Nate has your email addresses already, which we will need later.

**Comment by frouioui** [comment]
Hello @aliok and @nate-double-u, I can see the [project being added to the LFX website](https://mentorship.lfx.linuxfoundation.org/project/8299d27a-9e36-4de6-abbc-c9282634ee03), is it possible to add myself to the list of mentors? Right now only @rohit-nayak-ps is listed among the mentors.

**Pull request merged**
