### PR TITLE
24' Fall - Add Kyverno project ideas (part 2)

### PR DESCRIPTION
**Pull request by eddycharly**
Late kyverno project ideas.

### CODE REVIEW

**Comment by eddycharly** [comment]
cc @vishal-chdhry @nate-double-u

**Review by nate-double-u — COMMENTED** [review]
Thanks for this @eddycharly!

@vishal-chdhry could you 👍 or approve this PR to confirm your participation?

**Comment by MariamFahmy98** [comment]
@eddycharly - I noticed that my email is wrong for the other two projects. Is it possible to modify it as well?
My email is mariam.fahmy@nirmata.com

**Comment by nate-double-u** [comment]
@MariamFahmy98 I've corrected both the projects in the LFX platform so you're now listed as a mentor correctly. Thanks for letting us know!

**Review by vishal-chdhry — APPROVED** [review]

**Review by nate-double-u — APPROVED** [review]
Thanks everyone!

**Pull request merged**
