### PR TITLE
Add prometheus/otel project idea

### PR DESCRIPTION
**Pull request by ArthurSens**
cc @aknuds1

Opening as a draft because we're 2 Prometheus maintainers wanting to work on open-telemetry projects.

@dashpole, @aneurysm9, do we have your blessing to work on this? :)

### CODE REVIEW

**Comment by nate-double-u** [comment]
Cool idea, love seeing cross project collaborations!

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
I believe @rapphil is the other codeowner of the prometheusremotewrite exporter.

**Comment by rapphil** [comment]
TIL about the mentoring program. Good initiative. I would like to be in the loop if possible as observer (besides what is publicly visible).

**Review by rapphil — APPROVED** [review]

**Comment by ArthurSens** [comment]
> TIL about the mentoring program. Good initiative. I would like to be in the loop if possible as observer (besides what is publicly visible) - this is just to help me understand how this process work and to get contact with you folks :).

Of course! The mentoring program is mostly about integrating new folks into the community while delivering something useful to all. We will focus the work on public community channels and use private ones just for periodic synchronous communication. We can definitely invite you to our meeting notes

**Review by aknuds1 — APPROVED** [review]

**Review by nate-double-u — APPROVED** [review]
Thanks everyone!

**Pull request merged**
