### PR TITLE
 Moving proposals to accepted (LFX Mentorship 2023 term 1: March - May)

### PR DESCRIPTION
**Pull request by nate-double-u**
* adding Konveyor projects
* adjusting the ToC layout (pushing it to the left two spaces)

"deploy preview:" https://github.com/nate-double-u/cncf-mentoring/tree/2023-01-Mar-May-Proposals-pt5/lfx-mentorship/2023/01-Mar-May

### CODE REVIEW

**Review by jaytiaki — APPROVED** [review]
/lgtm

**Comment by nate-double-u** [comment]
LFX approved and accepting applications.

**Pull request merged**
