### PR TITLE
LFX Summer 03 - TAG Network

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

### CODE REVIEW

**Comment by nate-double-u** [comment]
Could this be a Meshery project, @leecalcote?

**Comment by leecalcote** [comment]
@nate-double-u, thanks for asking. It's Meshery related (Meshery uses MeshModels) and as an initiative also stands alone in terms of an independent unit of value to other people / other projects. We do track this work in one of the TAG Network working groups and take what opportunity we can to highlight interns/contributors under the TAG Network flag when the opportunity arises (example from KubeCon EU - https://twitter.com/theBeginner86/status/1649062836268843012?s=20), but you're right that it could be categorized either way. If you consider that this might fit more comfortably under Meshery as the category, let's do it. Either way is 👍

**Comment by nate-double-u** [comment]
I think it'd be easier if we could shift it to Meshery (if it's not too much trouble).

**Review by nate-double-u — APPROVED** [review]

**Comment by nate-double-u** [comment]
Just a note, i shifted this project to fall under Meshery when i resolved the conflicts.

**Pull request merged**
