### PR TITLE
Flux and WasmEdge details added

### PR DESCRIPTION
**Pull request by Srishtihere**
with reference to issue #997 I have made the require changes

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Thanks @Srishtihere!

**Comment by nate-double-u** [comment]
Before I merge this in, we'll need you to sign the commits.
Please see the instructions here: https://github.com/cncf/mentoring/pull/1075/checks?check_run_id=16419405020

**Comment by Srishtihere** [comment]
done signing off. Thank you

**Comment by nate-double-u** [comment]
Great, thanks!

**Pull request merged**
