### PR TITLE
Cilium: add sub project voting issue

### PR DESCRIPTION
**Pull request by xmulligan**
related: https://github.com/cilium/community/issues/82

### CODE REVIEW

**Review by aliok — APPROVED** [review]
LGTM!

@nate-double-u I leave the final approval to you, since the LFX platform side might need some work.

**Review by nate-double-u — COMMENTED** [review]
@xmulligan could you refactor this into the README file -- this project has been accepted.

**Review by nate-double-u — CHANGES_REQUESTED** [review]
@xmulligan could you refactor this into the README file -- this project has been accepted.

**Comment by xmulligan** [comment]
replace by https://github.com/cncf/mentoring/pull/1152

**Pull request closed without merging**
