### PR TITLE
LFX mentorship 2024_03: add Antrea project idea

### PR DESCRIPTION
**Pull request by antoninbas**

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Thanks for this @antoninbas!

Before we merge this in, could @tnqn and @Dyanngg provide a 👍 or approve this PR to confirm participation?

**Review by Dyanngg — APPROVED** [review]
LGTM, thanks @antoninbas for opening the proposal

**Review by tnqn — APPROVED** [review]
LGTM

**Review by aliok — APPROVED** [review]
Thanks @antoninbas and other mentors for creating a **great** project description (we don't have that often) 🎉

**Pull request merged**
