### PR TITLE
KubeVela: Support more clouds

### PR DESCRIPTION
**Pull request by zzxwill**
Empower KubeVela to support more Cloud providers and Cloud resources.

### CODE REVIEW

**Review by idvoretskyi — APPROVED** [review]

**Comment by nate-double-u** [comment]
Hello,

We've been asked to provide some more information about the projects. 

As per the [Defining a Project Idea list](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list), could you please update any project suggestions you've submitted with the following (if not already provided):

a) a project title/description 
b) more detailed description of the project (2-5+ sentences) 
c) expected outcomes 
d) skills required/preferred 
e) possible mentors 
f) expected size of the project (175 or 350 hours) 
g) an easy, medium, or hard difficulty rating of each project.

Please update your projects by March 3, 2022. Thanks!

**Comment by zzxwill** [comment]
> Hello,
> 
> We've been asked to provide some more information about the projects.
> 
> As per the [Defining a Project Idea list](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list), could you please update any project suggestions you've submitted with the following (if not already provided):
> 
> a) a project title/description b) more detailed description of the project (2-5+ sentences) c) expected outcomes d) skills required/preferred e) possible mentors f) expected size of the project (175 or 350 hours) g) an easy, medium, or hard difficulty rating of each project.
> 
> Please update your projects by March 3, 2022. Thanks!

Sure. Thanks.

**Comment by zzxwill** [comment]
@nate-double-u Updated. Thanks for your instruction.
https://github.com/oam-dev/kubevela/issues/2442

**Comment by nate-double-u** [comment]
Please see the umbrella issue: https://github.com/cncf/mentoring/issues/523

Note we have a new deadline: **Tues, March 1 at 5pm PT**.

**Comment by nate-double-u** [comment]
> @nate-double-u Updated. Thanks for your instruction. [oam-dev/kubevela#2442](https://github.com/oam-dev/kubevela/issues/2442)

@zzxwill please update the `summerofcode/2022.md` as well. Are you able to update the other projects?

**Comment by zzxwill** [comment]
Done https://github.com/cncf/mentoring/pull/539. Thanks:)

**Pull request merged**
