### PR TITLE
Moved archive info form readme to the archive file

### PR DESCRIPTION
**Pull request by Riaankl**
Part of Issue https://github.com/cncf/mentoring/issues/738

Will move the Cross folder in a next PR.
The is no Archive folder. 
We might want to make an `Achive` folder under `Programs` and move `Cross` and the `program-archives.md` file into that folder.

### CODE REVIEW

**Comment by jaytiaki** [comment]
I agree @Riaankl; Cross won't be a focal point for some time, so archiving it under a new dedicated folder works well.

**Comment by Riaankl** [comment]
> I agree @Riaankl; Cross won't be a focal point for some time, so archiving it under a new dedicated folder works well.
Thanks @jaytiaki 
I will create the folder and move Cross over in another PR.

**Comment by Riaankl** [comment]
Push a few more commits to clean up and fix broken links.

**Review by nate-double-u — COMMENTED** [review]
Since we are moving the file to be a folder index file, we should probably rename `programs/archive/program-archives.md` -> `programs/archive/README.md` so that when folks come to the folder it renders automatically.

**Comment by nate-double-u** [comment]
Looks good, as a follow up, could we take the 2022 stuff out of the archive - we can keep it as 'current'.

**Comment by Riaankl** [comment]
> Looks good, as a follow up, could we take the 2022 stuff out of the archive - we can keep it as 'current'.

@nate-double-u @jaytiaki I move the 2022 data to the programs/README.md as requested

**Review by nate-double-u — APPROVED** [review]
lgtm

**Pull request merged**
