### PR TITLE
Inspektor Gadget project proposals for LFX 2024 term 3

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Add Inspektor Gadget project proposals for LFX mentorship program 2024 term 3.

cc @alban @flyth @mqasimsarfraz @burak-ok

### CODE REVIEW

**Comment by nate-double-u** [comment]
Thanks for this @mauriciovasquezbernal!

Where possible, we prefer to have more than one mentor for a project. Is there anyone else who could help with _New gadget for detecting deadlocks_ and _Testing Inspektor Gadget gadgets on different kernel versions_?

@alban @flyth @mqasimsarfraz @burak-ok, could you each 👍 or approve this PR to confirm your participation?

**Comment by nate-double-u** [comment]
Sorry, I see you all have thumbs up already! (I should refresh before commenting, thanks everyone! 😅)

**Comment by mauriciovasquezbernal** [comment]
> Where possible, we prefer to have more than one mentor for a project. Is there anyone else who could help with New gadget for detecting deadlocks and Testing Inspektor Gadget gadgets on different kernel versions?

Sure, @alban and @burak-ok kindly offered to help with those two projects. Thanks!

**Review by nate-double-u — APPROVED** [review]
Thanks for the update!

**Pull request merged**
