### PR TITLE
Fix Kyverno mentorship description

### PR DESCRIPTION
**Pull request by chipzoller**
Fixes (for the last time) the [Implement new custom JMESPath filters](https://mentorship.lfx.linuxfoundation.org/project/bb0ff695-3d54-4ce2-b93c-3ab92842b3ee) mentorship listing.

### CODE REVIEW

**Comment by chipzoller** [comment]
@nate-double-u I apologize for yet another fix. I did a bad job of checking my work on the previous one. This is the last you'll hear from me :)

**Review by nate-double-u — APPROVED** [review]
Sorry for the delay @chipzoller, lgtm

**Comment by nate-double-u** [comment]
I've updated the LFX info as well.

**Comment by chipzoller** [comment]
Thanks much.

**Pull request merged**
