### PR TITLE
Add in-toto project ideas for LFX 2024 Term 2

### PR DESCRIPTION
**Pull request by PradyumnaKrishna**
cc @SantiagoTorres

### CODE REVIEW

**Comment by aliok** [comment]
Thanks @PradyumnaKrishna !

After I receive a 👍 or an approval from @SantiagoTorres , I will merge this PR.

**Review by SantiagoTorres — APPROVED** [review]

**Comment by SantiagoTorres** [comment]
My b! LGTM!

**Review by nate-double-u — APPROVED** [review]
Thanks @PradyumnaKrishna & @SantiagoTorres!

**Comment by nate-double-u** [comment]
I cleaned up the conflicts, and consolidated the in-toto projects under one heading.

**Pull request merged**
