### PR TITLE
GSOC: Add in-toto projects

### PR DESCRIPTION
**Pull request by mnm678**
cc @lukpueh @adityasaky

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Hi @mnm678,

Thanks for the project submissions. Unfortunately for this program we're only able to accept projects that are hosted under CNCF project orgs/repos. Since the second project is under the Jenkins repo, we wouldn't be able to support it. The first project can be merged in though.

**Comment by mnm678** [comment]
> Thanks for the project submissions. Unfortunately for this program we're only able to accept projects that are hosted under CNCF project orgs/repos. Since the second project is under the Jenkins repo, we wouldn't be able to support it. The first project can be merged in though.

I updated the pr, thanks!

**Review by nate-double-u — APPROVED** [review]

**Comment by nate-double-u** [comment]
Hello,

We've been asked to provide some more information about the projects. 

As per the [Defining a Project Idea list](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list), could you please update any project suggestions you've submitted with the following (if not already provided):

a) a project title/description 
b) more detailed description of the project (2-5+ sentences) 
c) expected outcomes 
d) skills required/preferred 
e) possible mentors 
f) expected size of the project (175 or 350 hours) 
g) an easy, medium, or hard difficulty rating of each project.

Please update your projects by March 3, 2022. Thanks!

**Comment by adityasaky** [comment]
Hi @nate-double-u, I'm working on updating the in-toto projects. I'll likely submit the changes with a new proposal we're working on.

**Comment by nate-double-u** [comment]
Please see the umbrella issue: https://github.com/cncf/mentoring/issues/523

Note we have a new deadline: **Tues, March 1 at 5pm PT**.

**Pull request merged**
