### PR TITLE
Add OpenELB ideas to GSoC

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Hi @idvoretskyi , could you please help to take a look at this PR? 

Thanks.

### CODE REVIEW

**Review by idvoretskyi — CHANGES_REQUESTED** [review]
The deadline has passed on Feb 14th, sorry :(

**Comment by nate-double-u** [comment]
Hi @FeynmanZhou, I think we closed this too soon. As Google doesn't prevent adding ideas to the ideas page after the organization application deadline, I'd like to reopen this PR and invite you to expand on it.

For each project, could you please update the description (should be 2-5 sentences) and add the following sections:
- Expected Outcome
- Expected Project Size: 175 or 350 hours
- Difficulty: Easy, Medium, or Hard

**Comment by nate-double-u** [comment]
Hi @FeynmanZhou, I think we closed this too soon. As Google doesn't prevent adding ideas to the ideas page after the organization application deadline, I'd like to reopen this PR and invite you to expand on it.

For each project, could you please update the description (should be 2-5 sentences) and add the following sections:
- Expected Outcome
- Expected Project Size: 175 or 350 hours
- Difficulty: Easy, Medium, or Hard

**Comment by FeynmanZhou** [comment]
> 

That's good news! Sure, I will update these sections soon. 

Thanks!

**Comment by nate-double-u** [comment]
Closing as the contributor submission deadline has passed.

**Pull request closed without merging**
