### PR TITLE
Fix email on mentoring projects

### PR DESCRIPTION
**Pull request by jesusvazquez**
Hello 👋 , 

Made a mistake setting up my email when my LFX account to be used was under my personal email. I was trying to look at the list of applicants on the projects and realized I couldn't see either applicants or projects.

My bad for not suggesting the right email 🙏  Please let me know if there is anything else to do to fix this.

### CODE REVIEW

**Comment by aliok** [comment]
@nate-double-u can you update @jesusvazquez 's email on LFX platform?

**Comment by nate-double-u** [comment]
Hi @jesusvazquez, I've been working with LFIT, and have you listed as a mentor in the backend, but think you need to create a mentor profile now. 

https://docs.linuxfoundation.org/lfx/mentorship/mentors/create-a-mentor-profile

**Comment by nate-double-u** [comment]
These email addresses are different from what LF supprot provided me. Have you set up a mentor profile before? If yes, which email address is the primary email address associated with that LFID?

**Comment by jesusvazquez** [comment]
Hey @nate-double-u sorry I messed up the emails again, now finally corrected.

The LFX platform shows I have a mentor profile for this last email 
image

**Comment by nate-double-u** [comment]
Thanks, I'll make the updates!

**Review by nate-double-u — APPROVED** [review]
@jesusvazquez you're listed now! 😊

Thanks for your patience through this process.

**Comment by jesusvazquez** [comment]
Working, thanks!

**Pull request merged**
