### PR TITLE
add cri-o lfx project for term 1 2024

### PR DESCRIPTION
**Pull request by haircommander**

### CODE REVIEW

**Comment by nate-double-u** [comment]
This is late, but I think we can get it in. We'll load this into LFX shortly.

**Review by nate-double-u — APPROVED** [review]

**Comment by nate-double-u** [comment]
I'm not very familiar with CRI-O, so forgive this question: is this 12 weeks of full time work?

**Comment by haircommander** [comment]
good question! other than the pieces listed, some things they could work on are adding testing for the release process, as well as testing for the release notes process https://github.com/cri-o/cri-o/issues/6577. I think this area could use 12 weeks of work. Do you think that is sufficient

**Comment by nate-double-u** [comment]
Absolutely, if you think it's enough, that's good enough for me 🙂
(I trust you to scope the work, it looked a little thin, but like i say, i don't know the project very well. We'll get this loaded into LFX as soon as we can).

**Pull request merged**
