### PR TITLE
Q2'2020 participating projects listed

### PR DESCRIPTION
**Pull request by idvoretskyi**
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
@idvoretskyi projects still say pending approval?

**Comment by caniszczyk** [comment]
Also can you list the title of the project next to the link, thanks!

**Comment by idvoretskyi** [comment]
> @idvoretskyi projects still say pending approval?

This is weird, so I'll raise this to the Community Bridge product team.

> Also can you list the title of the project next to the link

This is fine for now, we'll add the project titles after CNCF projects will
make their decisions.

**Comment by idvoretskyi** [comment]
@caniszczyk FYI - I've updated the PR, added the Selected projects section where the selected project ideas will be listed (once mentors will make a selection).

**Pull request merged**
