### PR TITLE
Add project_ideas for KubeEdge

### PR DESCRIPTION
**Pull request by fisherxu**
Add project ideas  for KubeEdge community.

### CODE REVIEW

**Comment by nate-double-u** [comment]
Thanks for this @fisherxu, could you provide a bit more in the descriptions—2-5 sentences should be enough. Also, i note that the upstream issues are placeholders, could you update those as well?

**Comment by fisherxu** [comment]
@nate-double-u Have updated the description, ptal :)
 
cc @Shelley-BaoYue

**Review by nate-double-u — APPROVED** [review]
Thanks for making the updates @fisherxu! And thanks to the mentoring team (@Shelley-BaoYue)

**Pull request merged**
