### PR TITLE
Add a KubeVela mentoring project

### PR DESCRIPTION
**Pull request by chivalryq**
This PR add another KubeVela project for second term of 2023. And sorry for the late again. It'll be great if project this could be accepted.

### CODE REVIEW

**Comment by nate-double-u** [comment]
hi @chivalryq I can look at this tomorrow -- we can likely still add it as you're very near the deadline.

**Comment by chivalryq** [comment]
Thanks a lot! I'll solve the conflicts. @nate-double-u

**Comment by nate-double-u** [comment]
Hi @chivalryq, I don't see you on the Kubevela maintainers list, https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L925, we don't require maintainers to be the primary mentors but we do need maintainer approval. @Somefive, since you're tagged as a mentor in this proposal could you give this PR a 👍 or approval?

**Comment by Somefive** [comment]
> Hi @chivalryq, I don't see you on the Kubevela maintainers list, https://github.com/cncf/foundation/blob/main/project-maintainers.csv#L925, we don't require maintainers to be the primary mentors but we do need maintainer approval. @Somefive, since you're tagged as a mentor in this proposal could you give this PR a 👍 or approval?

Approved. @chivalryq has discussed with me. Thanks for the support! :)

**Comment by chivalryq** [comment]
ping @nate-double-u

**Review by nate-double-u — APPROVED** [review]

**Pull request merged**
