### PR TITLE
Update mentors of Kyverno proposed project ideas

### PR DESCRIPTION
**Pull request by prateekpandey14**
Update mentors of Kyverno proposed project ideas

### CODE REVIEW

**Comment by nate-double-u** [comment]
Hi @prateekpandey14, what is your preferred email address? (you can share it here, or DM me on CNCF slack)

**Comment by nate-double-u** [comment]
Hi @prateekpandey14 could you update this PR to resolve the conflicts?

**Comment by prateekpandey14** [comment]
@nate-double-u done.

**Comment by nate-double-u** [comment]
Hi @prateekpandey14, it looks like this PR is changing more than intended.

**Pull request closed without merging**
