### PR TITLE
LFX Summer 2024: CNCF TAG Network

### PR DESCRIPTION
**Pull request by leecalcote**

### CODE REVIEW

**Review by nate-double-u — COMMENTED** [review]
Hi @leecalcote, thanks for this!

@MUzairS15 & @nicholasjackson, could you 👍 or approve this PR to confirm your participation?

@leecalcote, Could you also resolve the merge conflicts?

**Comment by leecalcote** [comment]
@nate-double-u, you bet. Merge conflict eliminated (all other projects moved to readme.md).

**Review by nate-double-u — APPROVED** [review]
Thanks for the updates, and I see everyone has confirmed their participation! I'll merge this in now and load up the LFX platform.

**Comment by leecalcote** [comment]
Yesssss 😄

**Pull request merged**
