### PR TITLE
Add WasmEdge proposal for GSoD

### PR DESCRIPTION
**Pull request by alabulei1**
Because the proposal is too long, so I am inserting the link here. Let me know if it works. Thanks

### CODE REVIEW

**Comment by nate-double-u** [comment]
Thanks for the proposal! 

We are looking at the best way to manage several proposals with the GSoD program (https://groups.google.com/g/season-of-docs-discuss/c/PxTWKQfblLc). We'll keep you updated and review this proposal regardless of how GSoD suggests we proceed.

**Comment by alabulei1** [comment]
Got it. Thanks @nate-double-u  Please keep me informed of any updates regarding the submission.

**Comment by nate-double-u** [comment]
As per [the Google PMs comments](https://groups.google.com/g/season-of-docs-discuss/c/PxTWKQfblLc/m/nBrC8CRuAQAJ) about org applications:

> We still ask that each project apply separately; if a project is selected, they can choose CNCF as their payment option with Open Collective when we begin setting up grant payments.
> 
> Projects can feel free to add in their application that payments would be handled via CNCF but that's not a factor in our decision making for what projects to accept.

We ask that you submit this project directly with GSoD, rather than going through us (the CNCF). Sorry for the confusion around this @alabulei1.

**Comment by aliok** [comment]
> We ask that you submit this project proposal directly with GSoD, rather than going through us (the CNCF). Sorry for the confusion around this @alabulei1.

@alabulei1 I wanted to do my best and review the proposal but I cannot add any inline comments on the [Github discussion](https://github.com/WasmEdge/WasmEdge/discussions/2358).

I would be happy to do it if you create a PR somewhere (could be this repository too).

**Comment by alabulei1** [comment]
No worries. Well received and thanks for your help. @nate-double-u I will submit the proposal to GSoD after @aliok kindly helps me review the proposal. 

Hi @aliok I have created a repo called GSoD2023 under the WasmEdge project. You can find the proposal [here](https://github.com/WasmEdge/GSoD2023). Looking forward to your review. Thank you so much!

**Comment by aliok** [comment]
@alabulei1 I've added my comments here: https://github.com/WasmEdge/GSoD2023/pull/1

I think it looks good overall :) Thanks for putting it together.

**Comment by aliok** [comment]
/close

I am closing this one as we tracked the proposal in https://github.com/WasmEdge/GSoD2023/pull/1 and https://github.com/WasmEdge/GSoD2023/pull/2.

Thanks a lot @alabulei1

**Pull request closed without merging**
