### PR TITLE
Planning for LFX 2024 Term 02 Jun-Aug

### PR DESCRIPTION
**Pull request by nate-double-u**
Planning LFX 2024 Term 2, Jun-Aug

previous timeline for term 2: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug

| activity | date |
| --- | --- |   
| project proposals | Monday April 8 - Wed April 24, 2024, 5:00 PM PDT |
| mentee applications open | Monday April 29 - Tues May 14, 5:00 PM PDT |
| application review/admission decisions | Wed May 15 - Tues June 29, 5:00 PM PDT |
| selection notifications | Tues May 29, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Monday June 3 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wednesday July 10 10 (Week 6) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Wed Aug 21, 5:00 PM PST (Week 12) |
| Last day of term | Friday Aug 30 |

### CODE REVIEW

**Comment by nate-double-u** [comment]
Notes:

    The gap between project proposals closing and applications opening is for CNCF/LF staff to load proposals into the LFX platform and get LFX approvals

**Review by krook — APPROVED** [review]
Seems reasonable to me

**Review by Swil78 — APPROVED** [review]
LGTM

**Review by aliok — APPROVED** [review]
LGTM!

**Comment by nate-double-u** [comment]
Thanks for the reviews folks!

**Pull request merged**
