### PR TITLE
Adding remaining LFX 2024 Term 2 projects to approved

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding Meshery, CNCF TAG Network, and K8s Sig Project Kubespray projects to approved projects

/hold for LFX approval

@leecalcote @muzairs15 @nicholasjackson @yankay @mzaian @Yahsharma1911 @aabidsofi19 @gyohuangxin you should all have received emails to join your specific projects.

### CODE REVIEW

**Comment by nate-double-u** [comment]
@yankay, I don't think we have your correct email address -- we need to use the one you use for your LFID. Also, now we've created a new project for you, could you [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f)?

**Comment by yankay** [comment]
> @yankay, I don't think we have your correct email address -- we need to use the one you use for your LFID. Also, now we've created a new project for you, could you [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f)?

Thanks @nate-double-u 

My LFID Email Address is yankay.com@gmail.com , and my profile is https://openprofile.dev/profile/yankay .

I tried to [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f, but it seems it has been closed, And I have no permission to delete it.

image

**Comment by Yashsharma1911** [comment]
@nate-double-u I haven't received any email yet, I think we mistakenly added wrong github id of mine if that causing issue, it is @Yashsharma1911 instead of "@Yahsharma1911"

**Review by nate-double-u — COMMENTED** [review]
We're waiting on one remaining approval, but let's merge this in as is, we can make changes as a follow up as needed.

**Comment by nate-double-u** [comment]
> > @yankay, I don't think we have your correct email address -- we need to use the one you use for your LFID. Also, now we've created a new project for you, could you [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f)?
> 
> Thanks @nate-double-u
> 
> My LFID Email Address is [yankay.com@gmail.com](mailto:yankay.com@gmail.com) , and my profile is https://openprofile.dev/profile/yankay .
> 
> I tried to [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f, but I have no permission to delete it .
> 
> image

Hi @yankay i've updated the project. please let me know if you're able to access it.

**Comment by nate-double-u** [comment]
> @nate-double-u I haven't received any email yet, I think we mistakenly added wrong github id of mine if that causing issue, it is @Yashsharma1911 instead of "@Yahsharma1911", however I have created a mentor profile if that was the ask from the email I suppose to join the project

I don't think the github id is the issue. We need to use the same email address as you use for your LFID. Please let me know if the one in this PR is correct.

**Comment by Yashsharma1911** [comment]
> > @nate-double-u I haven't received any email yet, I think we mistakenly added wrong github id of mine if that causing issue, it is @Yashsharma1911 instead of "@Yahsharma1911", however I have created a mentor profile if that was the ask from the email I suppose to join the project
> 
> I don't think the github id is the issue. We need to use the same email address as you use for your LFID. Please let me know if the one in this PR is correct.

Thanks @nate-double-u for confirming, I've reverified email is correct and also after creating a mentor profile, project with my mentor profile is updated 👍

**Comment by yankay** [comment]
> > > @yankay, I don't think we have your correct email address -- we need to use the one you use for your LFID. Also, now we've created a new project for you, could you [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f)?
> > 
> > 
> > Thanks @nate-double-u
> > My LFID Email Address is [yankay.com@gmail.com](mailto:yankay.com@gmail.com) , and my profile is https://openprofile.dev/profile/yankay .
> > I tried to [close your original one](https://mentorship.lfx.linuxfoundation.org/project/754cd85c-b503-491c-840e-b8bbbd35fe5f, but I have no permission to delete it .
> > image
> 
> Hi @yankay i've updated the project. please let me know if you're able to access it.

HI @nate-double-u 

I can access https://mentorship.lfx.linuxfoundation.org/project/22b0ef86-d390-4ea2-b302-79e819dcbdfc , Thank you very much

**Pull request merged**
