### PR TITLE
Proposal of Vitess/Arewefastyet project for LFX 2024 Jun-Aug

### PR DESCRIPTION
**Pull request by frouioui**
Here is the proposal to add Vitess/Arewefastyet as a LFX 2024 project.

### CODE REVIEW

**Comment by frouioui** [comment]
@nate-double-u can you merge mine first please? I have added the table of content and other content to the README.

**Comment by nate-double-u** [comment]
Hi @frouioui, sure, I'll review this afternoon and will be sure to get yours in first.

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Hi @frouioui,

proposals should target the [project_ideas.md ](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md)file (part of our process is moving the ideas over to the readme on approval from LFX).

Also, we prefer having 2 mentors per project if available -- is there someone else you'd be able to recruit as a second?

**Comment by nate-double-u** [comment]
Also, thanks for getting your proposal in on the original due date -- we have updated [this term's schedule](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/README.md) to push things back a couple weeks, and the new due date is May 8th.

**Comment by frouioui** [comment]
> Also, we prefer having 2 mentors per project if available

I have added @notfelineit as a mentor. She is also a Vitess maintainer and has experience with React/TypeScript which is required to work on this internship.

**Comment by frouioui** [comment]
> proposals should target the [project_ideas.md ](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md?rgh-link-date=2024-04-25T00%3A18%3A46Z)file

Got it, apologies for the oversight. Fixed via 8b89711.

**Review by nate-double-u — APPROVED** [review]
Thanks @frouioui & @notfelineit

**Pull request merged**
