### PR TITLE
doc: added cluster api provider aws project

### PR DESCRIPTION
**Pull request by richardcase**
This adds a project idea for the spring 23 mentorship program for the Cluster API Provider AWS project.

### CODE REVIEW

**Comment by Nandini99-git** [comment]
I would like to work on this.

**Comment by richardcase** [comment]
@nate-double-u (and anyone else) - do you know if there are any AWS accounts that the selected mentees could use for the duration of the mentorship program?

(for CAPG there are GCP account that the mentees are added to for the duration of the program)

**Comment by nate-double-u** [comment]
> I would like to work on this.

Hi @Nandini99-git, I appreciate your enthusiasm! We are still in the project proposal phase, but you should feel free to take a look a the upstream issue and start discussing it with the Cluster API team.

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Thanks for this @richardcase!

We'll do some research on the AWS question, but i don't think it's a show stopper for the project.

~However, we do need a maintainer to participate in mentorship projects -- are you able to add someone from the [K8s maintainers group](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) to work with you as a mentor as well?~

Edit: since you're a [sub-project maintainer](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/OWNERS_ALIASES#L24-L25) there's no further need for another mainainer's participation. Sorry for the confusion!

**Review by nate-double-u — APPROVED** [review]

**Pull request merged**
