### PR TITLE
Add Kyverno proposal

### PR DESCRIPTION
**Pull request by realshuting**

### CODE REVIEW

**Review by idvoretskyi — APPROVED** [review]

**Comment by anishagg17** [comment]
Hey, @realshuting is this up for internship?

**Comment by realshuting** [comment]
@idvoretskyi I resolved the conflict, please check it.

**Comment by realshuting** [comment]
@anishagg17 yes it's open for contributing.

**Comment by anishagg17** [comment]
> @anishagg17 yes it's open for contributing.

Yes, but any internship opportunity?

**Comment by idvoretskyi** [comment]
@anishagg17 this is a project proposal. Mentees will be able to apply after January 31st.

**Pull request merged**
