### PR TITLE
add KubeEdge LFX 2024 term3 ideas

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
Add KubeEdge LFX 2024 term3 ideas. PTAL 😄

### CODE REVIEW

**Review by nate-double-u — COMMENTED** [review]
Thanks for this @Shelley-BaoYue!

Could @WillardHu, @wbc6080, @tangming1996, @CreativityH, @MooreZheng, @hsj576, and @fisherxu each provide a 👍 or approve this PR to confirm their participation?

**Comment by hsj576** [comment]
\lgtm

**Comment by WillardHu** [comment]
👍

**Comment by tangming1996** [comment]
👍

**Comment by nate-double-u** [comment]
Hi, thanks for confirming folks, I'm still waiting for @CreativityH & @MooreZheng. The PR was opened before the due date so don't worry about the timeline (tho I'd like to get all the proposals wrapped by Monday. The sooner the better tho)

**Review by nate-double-u — APPROVED** [review]
Thanks everyone!

**Pull request merged**
