### PR TITLE
Add Notary and ORAS project ideas to lfx-mentorship

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Add Notary and ORAS project ideas to LFX mentorship program

cc @nate-double-u

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Thanks for this @FeynmanZhou!

However, we do need maintainer participation on all of the proposals.

Are you able to add a Notary maintainer for _HashiCorp Vault plugin for Notary_ and an ORAS maintainer for _Develop ORAS Website_?

Note: sometimes the [cncf/foundation/project-maintainer file](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) drifts out of date with who is and isn't a maintainer for these projects. If that is the case, could you open a PR to update the cncf/foundation maintainer list?

**Comment by FeynmanZhou** [comment]
@nate-double-u Okay. I will update the cncf/foundation maintainer list soon. 

Can we do this in parallel?

**Comment by nate-double-u** [comment]
Yes, I think that we can.

**Comment by nate-double-u** [comment]
Is there an up to date maintainer list for Notary or ORAS that you could link here?

**Comment by FeynmanZhou** [comment]
> Is there an up to date maintainer list for Notary and ORAS that you could link here?

@nate-double-u 
Thanks! Yes. There are four maintainers that I added as mentors for Notary and ORAS in this PR. 

For ORAS, Shiwei Zhang (@shizhMSFT) and Sylvia Lei (@Wwwsylvia) are listed on the [ORAS-go OWNERS](https://github.com/oras-project/oras-go/blob/main/OWNERS.md) as the subproject owners. I am also adding myself as a subproject owner https://github.com/oras-project/oras-www/pull/83.

For Notary, we are changing the maintainer list from a team to individuals. Shiwei Zhang (@shizhMSFT) and Patrick Zheng (@patrickzheng200) will be added there soon.

I am just aware of this kind of problem in our OSS projects. We are working with the community org maintainers to update it and sync it to the CNCF maintainer list this week. I hope this will not block our submission for LFX mentorship. Thanks for your understanding.

**Review by nate-double-u — APPROVED** [review]
Thanks for the updates @FeynmanZhou

**Pull request merged**
