### PR TITLE
LFX 24 Term 3: Service Mesh Performance

### PR DESCRIPTION
**Pull request by Yashsharma1911**
cc @leecalcote

### CODE REVIEW

**Review by nate-double-u — COMMENTED** [review]
Thanks for this @Yashsharma1911!

@leecalcote & @gyohuangxin, could you both either 👍 or approve this PR to confirm your participation?

**Comment by Yashsharma1911** [comment]
Conflict resolved

**Comment by nate-double-u** [comment]
We're still waiting for confirmation (a 👍 or PR approval) from @leecalcote & @gyohuangxin before we can merge this in.

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Review by nate-double-u — APPROVED** [review]
I see everyone has confirmed, thanks!

I think LFX approvals may be a couple days b/c the approvers are in a timezone that's heading into the weekend now. I'll load this into the platform, but approvals may take til Monday.

**Pull request merged**
