### PR TITLE
Feat: add KubeVela auto-generator  proposal for LFX 2023

### PR DESCRIPTION
**Pull request by FogDong**
Add KubeVela auto-generator proposal for LFX 2023.

Ref: kubevela/kubevela#5364

### CODE REVIEW

**Comment by wonderflow** [comment]
Ping @Somefive

**Comment by Somefive** [comment]
> Hi @FogDong, thanks for this proposal!
> 
> We do need a maintainer to participate in mentorship projects -- are you able to add someone from the KubeVela maintainers group to work with you as a mentor as well?
> 
> @wonderflow is this a project you'd be able to participate in along with [the other](https://github.com/cncf/mentoring/pull/764)?

I will be working with Fog on this mentoring project. Thanks!

**Comment by nate-double-u** [comment]
Thanks @Somefive! @FogDong, I can merge this when you add Da Yin to the mentor list.

**Comment by FogDong** [comment]
@nate-double-u Done. Thanks for the review!

**Review by nate-double-u — APPROVED** [review]

**Pull request merged**
