### PR TITLE
Add ideas from Istio docs WG

### PR DESCRIPTION
**Pull request by craigbox**

### CODE REVIEW

**Review by aliok — APPROVED** [review]
@craigbox can you find a back up mentor, just in case?

**Comment by craigbox** [comment]
Yes, but not by the deadline.

**Comment by nate-double-u** [comment]
Thanks for this @craigbox 

Also, we've extended the proposal window, project proposals are now due July 30, 2024 (https://github.com/cncf/mentoring/discussions/1263)

**Comment by aliok** [comment]
@craigbox Let's keep this PR on hold if that's ok, until you find a co-mentor, or until the deadline is close.

**Comment by craigbox** [comment]
Is a co-mentor a hard requirement?

**Comment by aliok** [comment]
>  Is a co-mentor a hard requirement?

No, it is not. That's why I said we can merge this PR when we're close to the deadline, even if there's no co-mentor.

I am pretty sure you will do a great job without a co-mentor, but mentors are encouraged to find co-mentors in general due to unexpected situations (sickness, family issues, etc).

**Comment by kairveeehh** [comment]
@craigbox  , I would like to take up this issue under lfx fall phase , could you please assign it to me?

**Comment by nate-double-u** [comment]
> @craigbox , I would like to take up this issue under lfx fall phase , could you please assign it to me?

Hi @kairveeehh, I appreciate your enthusiasm, but this isn't the issue to discuss candidate selections. We'll be opening applications up for candidates next week. Instructions for how to apply can be found in the [Program Guidelines](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md#program-guidelines). 

The best way to show your skills is to apply when applications are open!

**Review by nate-double-u — APPROVED** [review]

**Pull request merged**
