### PR TITLE
add KubeEdge project ideas for LFX March - May term

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
Add project ideas for KubeEdge community.

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Thanks for this @Shelley-BaoYue, @willardHu, and @fisherxu!

Could you add a second mentor to the proposals with only one? This year we're suggesting having at least two mentors per project.

**Comment by Shelley-BaoYue** [comment]
> Thanks for this @Shelley-BaoYue, @WillardHu, and @fisherxu!
> 
> Could you add a second mentor to the proposals with only one? This year we're suggesting having at least two mentors per project.

I have added 😄

**Comment by aliok** [comment]
I wanted to let you know that this term we’re doing an information session for mentors. We’d like to invite all the mentors participating to attend one of these if you're able:
* North America: [Jan 29, 2024 10:30 AM (Pacific Time)](https://zoom-lfx.platform.linuxfoundation.org/meeting/99504894798?password=54a6ec2f-d649-432b-a918-acd17720f163)
* EMEA + APAC: [Jan 30, 2024 8:00 AM (UTC)](https://zoom-lfx.platform.linuxfoundation.org/meeting/93514971498?password=907d67b6-3e04-42d3-afdc-52d288122c6f)

Can the other mentors give a thumbs up please? cc  @WillardHu, and @fisherxu!

Thanks folks

**Review by aliok — APPROVED** [review]

**Review by nate-double-u — APPROVED** [review]
Thanks for the update!

**Pull request merged**
