### PR TITLE
LFX menthorship: add Kyverno project ideas

### PR DESCRIPTION
**Pull request by realshuting**
This PR adds 4 Kyverno project ideas for 2024 Spring term.

### CODE REVIEW

**Review by nate-double-u — COMMENTED** [review]
Thanks for this @realshuting, @eddycharly, @JimBugwadia, @khaledEmaraDev, @anusha94, @MariamFahmy98, and @vishal-chdhry!

Are you able to add a second mentor to the "Kyverno for Envoy Auth" project? This year we're suggesting having at least 2 mentors per project.

**Comment by realshuting** [comment]
> Thanks for this @realshuting, @eddycharly, @JimBugwadia, @KhaledEmaraDev, @anusha94, @MariamFahmy98, and @vishal-chdhry!
> 
> Are you able to add a second mentor to the "Kyverno for Envoy Auth" project? This year we're suggesting having at least 2 mentors per project.

Hi @nate-double-u - I have added the second mentor, thanks!

**Review by nate-double-u — APPROVED** [review]
Thanks for the update @realshuting, and @anushkamittal2001 for joining!

I also wanted to let you know that this term we’re doing an information session for mentors. We’d like to invite all the mentors participating to attend one of these if you're able:
* North America: [Jan 29, 2024 10:30 AM (Pacific Time)](https://zoom-lfx.platform.linuxfoundation.org/meeting/99504894798?password=54a6ec2f-d649-432b-a918-acd17720f163)
* EMEA + APAC: [Jan 30, 2024 8:00 AM (UTC)](https://zoom-lfx.platform.linuxfoundation.org/meeting/93514971498?password=907d67b6-3e04-42d3-afdc-52d288122c6f)

**Comment by realshuting** [comment]
> Thanks for the update @realshuting, and @anushkamittal2001 for joining!
> 
> I also wanted to let you know that this term we’re doing an information session for mentors. We’d like to invite all the mentors participating to attend one of these if you're able:
> 
> * North America: [Jan 29, 2024 10:30 AM (Pacific Time)](https://zoom-lfx.platform.linuxfoundation.org/meeting/99504894798?password=54a6ec2f-d649-432b-a918-acd17720f163)
> * EMEA + APAC: [Jan 30, 2024 8:00 AM (UTC)](https://zoom-lfx.platform.linuxfoundation.org/meeting/93514971498?password=907d67b6-3e04-42d3-afdc-52d288122c6f)

Thanks for the information, we will join accordingly!

**Pull request merged**
