### PR TITLE
Added idea for Knative Eventing observability

### PR DESCRIPTION
**Pull request by aslom**

### CODE REVIEW

**Comment by nate-double-u** [comment]
I'm sorry @aslom, the deadline to submit the project ideas was February 14, 2022. I'd welcome this idea for Knative in the next cycle!

**Comment by aliok** [comment]
@nate-double-u , this idea was written in Knative GSoC ideas page here: https://github.com/knative/community/blob/main/google-summer-of-code/gsoc-2022.md

Knative was going to apply as a separate organization but after talking to CNCF, we decided that we won't apply separately and we will participate under CNCF if/when Knative is voted to be an accepted project. That voting happened last week and @aslom added the idea as soon as possible to this page.

Can we add this idea? Once it is added here, we will write a note in the Knative [GSoC ideas page](https://github.com/knative/community/blob/main/google-summer-of-code/gsoc-2022.md) that we moved to CNCF.

cc @idvoretskyi

**Comment by nate-double-u** [comment]
Hi @aliok, I'm sorry, but it isn't our deadline. [Google's deadline for the mentoring organization application](https://developers.google.com/open-source/gsoc/timeline) was February 21st, and they have already published the list of [accepted mentoring organizations](https://summerofcode.withgoogle.com/). At this point, I don't think we can get you in for this cycle.

I can set up the next cycle's files and invite you to open this PR against those so that we don't lose track of this project between now and when it starts. But I'm afraid there's little we can do for this cycle.

**Comment by aliok** [comment]
> Hi @aliok, I'm sorry, but it isn't our deadline. [Google's deadline for the mentoring organization application](https://developers.google.com/open-source/gsoc/timeline) was February 21st, and they have already published the list of [accepted mentoring organizations]

@nate-double-u, Google doesn't prevent adding ideas to the ideas page after the organization application deadline. I don't see anything in the program rules about that. Ideas in the ideas page are just hints for the potential contributors anyway. Contributors can even propose projects that are not in the ideas page.

**Comment by nate-double-u** [comment]
@aliok, @aslom, I apologize. After some discussion and research, I've found that we can add projects after the org gets accepted, until April 3. I'll reopen this so we can review the PR.

Sorry about the confusion, and I'm very happy we can include your project!

**Comment by aliok** [comment]
Thanks @nate-double-u :)

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Could you add an "Expected Outcome" section?

**Review by nate-double-u — APPROVED** [review]
Thanks @aslom!

**Comment by djdongjin** [comment]
Hi @nate-double-u , since projects can be added after org is accepted, should other closed PR be reopened? e.g., #518 #517

**Comment by nate-double-u** [comment]
Yes, these should be reconsidered. My todo list today includes revisiting previously closed PRs in this situation. I appreciate you linking those, I'll take a look shortly.

**Comment by nate-double-u** [comment]
Hi, I need to invite the mentors to the CNCF Org on summerofcode.withgoogle.com, but I don't have your email addresses. Could the mentors please fill out this form: https://forms.gle/339NecJLfXPuDahh8

**Comment by aslom** [comment]
Unable to access @nate-double-u @aavarghese @lionelvillard
image

**Comment by aavarghese** [comment]
> https://forms.gle/339NecJLfXPuDahh8

same

**Pull request merged**
